In [ ]:
import torch
# imports pytorch

In [ ]:
import numpy as np
# imports numpy

**Simple Tensor Operations**

In [ ]:
a = torch.empty(3,4)
a.size()
# creates an empty tensor of shape (3,4)

torch.Size([3, 4])

In [ ]:
a.fill_(3.14)
# inplace operations are suffixed with an underscore
# fills all the elements of tensor a with 3.14

tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])

In [ ]:
a.mean()
# computes the average of the tensor a
# even a single element of a tensor is a tensor (0D)

tensor(3.1400)

In [ ]:
a[1,2]
# even a single element of a tensor is a tensor (0D)

tensor(3.1400)

In [ ]:
a.std()
# returns the standard deviation of elements in tensor a

tensor(4.9804e-07)

In [ ]:
a.sum()
# returns the sum of elements in tensor a

tensor(37.6800)

In [ ]:
a.sum().item()
# to convert a 0D tensor into a Python scalar, item() is used

37.679996490478516

**Vector/matrix Operations**

In [ ]:
x = torch.tensor([1.0, 3.0, 5.0])
y = torch.tensor([2.0, 4.0, 6.0])
x+y

tensor([ 3.,  7., 11.])

In [ ]:
x*y
# hadamard product

tensor([ 2., 12., 30.])

In [ ]:
x**2
# exponentiation

tensor([ 1.,  9., 25.])

In [ ]:
x**y
# element-wise exponentiation

tensor([1.0000e+00, 8.1000e+01, 1.5625e+04])

In [ ]:
m=torch.tensor([[1.0, 0.0, 0.0],[0.0, 2.0, 0.0],[0.0, 0.0, 3.0]])
# matrix (2D tensor) intialization

In [ ]:
m.mv(x)
# matrix-vector product

tensor([ 1.,  6., 15.])

In [ ]:
m@x
# another form for the matrix-vector product

tensor([ 1.,  6., 15.])

**Slicing is similar to Numpy**

In [ ]:
a=torch.empty(2,5).random_(10)
a
# initialize the tensor with random integers below 10

tensor([[0., 2., 9., 5., 1.],
        [4., 4., 5., 6., 1.]])

In [ ]:
a[0]

tensor([0., 2., 9., 5., 1.])

In [ ]:
a[1]

tensor([4., 4., 5., 6., 1.])

In [ ]:
a[:,3:]
# slicing the tensor with a range

tensor([[5., 1.],
        [6., 1.]])

In [ ]:
a[:,1:3] = -1.0
a

tensor([[ 0., -1., -1.,  5.,  1.],
        [ 4., -1., -1.,  6.,  1.]])

In [ ]:
b = a.clone() # Clone a into b; changes in b will not be reflected in a
b[b == -1] = 2
b
# Boolean indexing

tensor([[0., 2., 2., 5., 1.],
        [4., 2., 2., 6., 1.]])

**High demnsional tensors**

In [ ]:
za = torch.zeros(1,3)
a.dtype, a.device
# default tensor is float32 type stored in CPU memory

(torch.float32, device(type='cpu'))

In [ ]:
#a=a.to(torch.float64)
a=a.long()
a.dtype, a.device

(torch.int64, device(type='cpu'))

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")

  a = a.to(device)
a.dtype, a.device

(torch.int64, device(type='cuda', index=0))

In [ ]:
x=torch.tensor([[1, 2., 3],
                [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.t()
# transposing a tensor

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
x.view(-1)
# reduce/reshape the tensor into a single dimensional (1D) tensor
# in the raster-scan order (rows first then columns)

tensor([1., 2., 3., 4., 5., 6.])

In [ ]:
x.view(3,-1)
# reshape into a tensor with 3 rows and whatever is the resulting columns
# in the raster-scan order

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
x.view(1,2,3).expand(3,2,3)

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

**Pytorch is an immense library of tensor operations. Visit documentation for a better idea and practice more to familiarize the important operations.**


**For efficiency reasons, different tensors share the same data, therefore need to be careful when modifying. By default, do not assume that two tensors refer to different data in memory**

In [ ]:
a = torch.full((2,5),2)
a

tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]])

In [ ]:
b=a.view(-1)
b

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
a[1,4]=10
a

tensor([[ 2,  2,  2,  2,  2],
        [ 2,  2,  2,  2, 10]])

In [ ]:
b
b[1] = 9

In [ ]:
a

tensor([[ 2,  9,  2,  2,  2],
        [ 2,  2,  2,  2, 10]])

**Broadcasting and Einstein Summations**

In [ ]:
# Broadcasting automatically expands the dimensions by replicating coefficients (when required)
x = torch.empty(100,3).normal_(3)
x.mean(0)

tensor([3.1387, 3.1124, 2.9805])

In [ ]:
x -= x.mean(0)
# we subtract 1 X 3 tensor from 100 X 3 tensor; it should result in an error, but it works!

x.mean(0)

tensor([ 2.2411e-07,  3.9816e-07, -2.8610e-08])

In [ ]:
A = torch.tensor([[1.],[2.],[3.],[4.],[5.]])
B = torch.tensor([[5., -5., 5., -5., 5.]])
print(A.shape,B.shape)
A+B

torch.Size([5, 1]) torch.Size([1, 5])


tensor([[ 6., -4.,  6., -4.,  6.],
        [ 7., -3.,  7., -3.,  7.],
        [ 8., -2.,  8., -2.,  8.],
        [ 9., -1.,  9., -1.,  9.],
        [10.,  0., 10.,  0., 10.]])

**Einsten Summation Convention**

Provides a concise way of describing dimension re-ordering, summing component wise products along some of them.

we can use for matrix multiplication, matrix-vector product, diagonal extraction, Hadamard product, batch matrix product, etc.

In [ ]:
A = torch.rand(2,5)
B = torch.rand(5,4)
torch.einsum('ij,jk->ik',A,B)

tensor([[1.4999, 1.2731, 1.4826, 1.9172],
        [0.2811, 0.9158, 0.7768, 0.5493]])

In [ ]:
A@B

tensor([[1.4999, 1.2731, 1.4826, 1.9172],
        [0.2811, 0.9158, 0.7768, 0.5493]])